apiVersion: v1
kind: Pod
metadata: 
  name: mysecondpod
  labels:
    app: pyservernew
spec:
  containers:
    - name: secondcontainerkube
      image: pyserver
      imagePullPolicy: Never
      ports:
        - name: py-port-new
          containerPort: 8080
      securityContext:
        privileged: true
        allowPrivilegeEscalation: true
      volumeMounts:
        - mountPath: /host/
          name: sc-storage-new
          mountPropagation: Bidirectional
  volumes:
    - name: sc-storage-new
      persistentVolumeClaim:
        claimName: pvc 