name: Building in Docker

on: 
  push:
    branches: master
jobs:
    run-build:
        runs-on: ubuntu-latest
        steps:
            - name: Copy the Repo 
              uses: actions/checkout@v1
            - name: Create the images
              run: |
                sudo docker build -t myassignment . 
                sudo docker build -t nginx_custom . -f Dockerfile_nginx 
            - name: Compose the Dockerfile
              run: |
                sudo docker-compose up
