name: "My tag workflow"

on: 
  pull_request:
    branches:
      - master
    types: ["closed"]
    paths:
      - README.md
    
jobs:
  tag-id:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tagId.outputs.tag }}
    steps:
      - name: Deploy Script
        uses: actions/github-script@c7971c2
        id: tagId
        with:
          script: |
            let head =  context.payload.pull_request.title.split('-');
            var tag;
            if( head != null )
            {
              tag = head[0]
            }
            core.setOutput('tag',tag);
            console.log(tag);
      - name: echo
        run: |
          echo $ {{ needs.tag-id.outputs.tag }}
  build:
    if: needs.tag-id.outputs.tag == 'hello'
    needs: tag-id
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        run: |
          cat  ./README.md | grep ABCD | awk '{ print \$2 }
      # - name: Create tag
      #   uses: actions/github-script@v3
      #   with:
      #     github-token: ${{ github.token }}
      #     script: |
      #       const { Octokit } = require("@octokit/rest");
      #       const octokit = new Octokit({
      #         auth: "4cebe563bfc51cd4e3db369dd7ae73499939cf93"
      #       });
      #       octokit.git.createTag({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         tag: needs.tag-id.outputs.tag,
      #         message: "Created by my-tag-workflow",
      #         object: context.sha,
      #         type: commit
      #       })