name: Repository dispatch

on: 
  repository_dispatch:
    
    
jobs:
  
     
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Script
        uses: actions/github-script@c7971c2
        id: tagId
        with:
          script: |
            console.log(context.job)
          
          
  
