name: "My tag workflow"

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: ["closed"]
    
    
jobs:
  
     
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Curl
        run: |
          echo "::set-output name=filepaths::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
          
  
