name: Repository dispatch

on: 
  repository_dispatch:
    
    
jobs:
  
     
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: | 
          echo "Workflow triggered by repository_dispatch"
          eval ${{ github.event }}
          
  
