name: Checking Git diff

on:
  push:
    branches:
      - git-diff

jobs:
  output-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@5a4ac90
      - name: Generate Difference
        run: |
          echo "::set-output name=diff::`diff -y  ./server.py ./clientnew.py || true`"
        id: gen-diff
      - name: Output the differences
        run: |
          echo ${{ steps.gen-diff.outputs.diff }}
      
