name: Static Code Analysis

on: [pull_request]

jobs:
    run-sca:
        runs-on: ubuntu-latest
        steps:
            - name: Copy the Repo
              uses: actions/checkout@v1
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install flake8 
            - name: Lint with flake8
              run: |
                export PATH="$HOME/.local/bin:$PATH"
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
           


