name: "My tag workflow"

on: 
  pull_request:
    branches:
      - master
    types: ["closed"]
    paths:
      - README.md
    
jobs:
  tag-id:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tagId.outputs.tag }}
    steps:
      - name: Deploy Script
        uses: actions/github-script@c7971c2
        id: tagId
        with:
          script: |
            let head =  context.payload.pull_request.title.split('-');
            var tag;
            if( head != null )
            {
              tag = head[0]
            }
            core.setOutput('tag',tag);
  build:
    needs: tag-id
    runs-on: ubuntu-latest
    steps:
      - name: Create tag
        uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            octokit.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: needs.tag-id.outputs.tag,
              message: "Created by my-tag-workflow",
              object: context.sha,
              type: commit
            })